<?php

return [
  'USERDEFAULTIMAGE' => 'default.png',
  'USERDEFAULTIMAGEPATH' => 'images',
  'USERIMAGEPATH' => 'storage/userImage',
  'USERIMAGEUPLOADPATH' => 'storage/userImage',
  'ATTACHMENTUPLOADPATH' => 'storage/attachment',
  'APP_NAME' => env('APP_NAME'),
  'APP_LOGO' => 'images/logo.png',
  'FAVICO_ICON' => 'images/favicon.png',
  'isMobile' => 1,
  "systemGeneratedRole" => 1,

  /* Date Time Format */
  'displayDateTimeFormatForAll' => "m/d/Y H:i",
  'displayDateTimeFormatWithAMPM' => "d/m/Y H:i A",
  'phpDisplayDateTimeFormatWithAMPM' => "m/d/Y h:i A",
  'displayDate' => "m/d/Y",
  'displayDateBlade' => "mm/dd/yyyy",
  'databaseStoredDateFormat' => "Y-m-d",
  'databaseStoredDateTimeFormat' => "Y-m-d H:i:s",
  'JsDisplayDateTimeFormatWithAMPM' => "MM/DD/YYYY hh:mm A",
  'JsDisplayDate' => "MM/DD/YYYY",
  'dateFormatFax' => "M Y",
  'fullDateFormatFax' => "M D, Y, H:i A",
  'displayTime' => "h:i A",
  'php12HoursTime' => 'h:i A',
  'frontSideDisplayDate' => 'd-F-Y h:i A',
  'roleSuperAdmin' => 1,
  'roleUser' => 2,
  'superAdminEmail'=>'laraveladmin@yopmail.com',
  /* Status   */
  'statusActive' => 'Active',
  'statusInActive' => 'Inactive',
  'statusActiveInt' => 1,
  'statusInActiveInt' => 0,
  'DEFAULT_TIMEZONE' => 'Asia/Calcutta',
  'STATUS_OPEN_INT' => 1,
  'STATUS_REOPEN_INT' => 2,
  'STATUS_CLOSE_INT' => 3,
  'STATUS_ONHOLD_INT' => 4,
  'STATUS_OPEN_TEXT' => 'Open',
  'STATUS_REOPEN_TEXT' => 'Reopen',
  'STATUS_CLOSE_TEXT' => 'Close',
  'STATUS_ONHOLD_TEXT' => 'Onhold',
];
